"""
Dim_Coaching generator — ONE file only.
Creates Dim_Coaching.csv in the sibling Data_Source folder.

Grain: one row = one coaching / intervention type.
This is not the coaching event log.
"""

from pathlib import Path

import pandas as pd

SAVE_FOLDER = Path(__file__).resolve().parent.parent / "Data_Source"
OUTPUT_FILE = SAVE_FOLDER / "Dim_Coaching.csv"

ACTIONS = [
    {
        "CoachingActionID": "ACT-01",
        "ActionName": "Floor side-by-side coaching",
        "ActionFamily": "Coaching",
        "DeliveryChannel": "Floor",
        "TriggerEvent": "Failed audit",
        "AppliesToCriticality": "Customer Critical|Business Critical",
        "IshikawaPillar": "People",
        "OwnerRole": "Supervisor",
        "RequiresSupervisor": True,
        "RequiresQaOwner": False,
        "SlaFeedbackHours": 48,
        "TypicalEffortMinutes": 45,
        "TypicalCostUsd": 85,
        "ExpectedScoreLiftHint": 0.18,
        "BestQmLink": "TOPS skill transfer after failed monitor; Feedback On Time 48h",
        "AmazonUseCase": "Wrong SOP on returns / missed promise",
    },
    {
        "CoachingActionID": "ACT-02",
        "ActionName": "Attribute-level refresher huddle",
        "ActionFamily": "Training",
        "DeliveryChannel": "Huddle",
        "TriggerEvent": "Repeat fail on same parameter",
        "AppliesToCriticality": "Customer Critical|Business Critical",
        "IshikawaPillar": "Process",
        "OwnerRole": "Supervisor",
        "RequiresSupervisor": True,
        "RequiresQaOwner": False,
        "SlaFeedbackHours": 48,
        "TypicalEffortMinutes": 20,
        "TypicalCostUsd": 40,
        "ExpectedScoreLiftHint": 0.12,
        "BestQmLink": "Repeat Fail Analysis + TNI",
        "AmazonUseCase": "KB adherence miss on refund timelines",
    },
    {
        "CoachingActionID": "ACT-03",
        "ActionName": "Compliance zero-tolerance briefing",
        "ActionFamily": "Compliance",
        "DeliveryChannel": "Teams",
        "TriggerEvent": "Fatal / CompC fail",
        "AppliesToCriticality": "Compliance Critical",
        "IshikawaPillar": "Compliance",
        "OwnerRole": "Quality Analyst",
        "RequiresSupervisor": True,
        "RequiresQaOwner": True,
        "SlaFeedbackHours": 48,
        "TypicalEffortMinutes": 30,
        "TypicalCostUsd": 120,
        "ExpectedScoreLiftHint": 0.22,
        "BestQmLink": "CompC Accuracy 99.5%; fail critical attribute fails the interaction",
        "AmazonUseCase": "PII read-back, gift-card code, skipped OTP",
    },
    {
        "CoachingActionID": "ACT-04",
        "ActionName": "Soft-skills empathy lab",
        "ActionFamily": "Training",
        "DeliveryChannel": "Classroom",
        "TriggerEvent": "Failed courtesy / ownership",
        "AppliesToCriticality": "Customer Critical",
        "IshikawaPillar": "People",
        "OwnerRole": "Trainer",
        "RequiresSupervisor": False,
        "RequiresQaOwner": False,
        "SlaFeedbackHours": 48,
        "TypicalEffortMinutes": 60,
        "TypicalCostUsd": 90,
        "ExpectedScoreLiftHint": 0.10,
        "BestQmLink": "Customer Critical example: rudeness / mistreating the customer",
        "AmazonUseCase": "DSAT on delay contacts, blamed the customer",
    },
    {
        "CoachingActionID": "ACT-05",
        "ActionName": "New-hire nest boost",
        "ActionFamily": "Nesting",
        "DeliveryChannel": "Nest desk",
        "TriggerEvent": "New hire failed audit",
        "AppliesToCriticality": "Customer Critical|Business Critical|Compliance Critical",
        "IshikawaPillar": "People",
        "OwnerRole": "Trainer",
        "RequiresSupervisor": True,
        "RequiresQaOwner": True,
        "SlaFeedbackHours": 48,
        "TypicalEffortMinutes": 90,
        "TypicalCostUsd": 110,
        "ExpectedScoreLiftHint": 0.11,
        "BestQmLink": "New Hire Performance Analysis; nesting certification",
        "AmazonUseCase": "Days 1-90, incomplete case notes + weak FCR",
    },
    {
        "CoachingActionID": "ACT-06",
        "ActionName": "Calibration realignment with Gauge",
        "ActionFamily": "Calibration",
        "DeliveryChannel": "Teams",
        "TriggerEvent": "Evaluator outside tolerance",
        "AppliesToCriticality": "Measurement",
        "IshikawaPillar": "Measurement",
        "OwnerRole": "Quality Manager",
        "RequiresSupervisor": False,
        "RequiresQaOwner": True,
        "SlaFeedbackHours": 48,
        "TypicalEffortMinutes": 40,
        "TypicalCostUsd": 60,
        "ExpectedScoreLiftHint": 0.15,
        "BestQmLink": "Attribute Reproducibility and Calibration Precision 90%",
        "AmazonUseCase": "QA scoring CompC tighter than Gauge",
    },
    {
        "CoachingActionID": "ACT-07",
        "ActionName": "SOP / KB article rewrite request",
        "ActionFamily": "Process Change",
        "DeliveryChannel": "BMS / ticket",
        "TriggerEvent": "Structural repeat fail across many agents",
        "AppliesToCriticality": "Business Critical",
        "IshikawaPillar": "Process",
        "OwnerRole": "Quality Lead",
        "RequiresSupervisor": False,
        "RequiresQaOwner": True,
        "SlaFeedbackHours": 0,
        "TypicalEffortMinutes": 240,
        "TypicalCostUsd": 400,
        "ExpectedScoreLiftHint": 0.28,
        "BestQmLink": "Driver Identification; close the loop on process opportunity",
        "AmazonUseCase": "Return-window article conflicts with live policy",
    },
    {
        "CoachingActionID": "ACT-08",
        "ActionName": "Knowledge-base targeted walkthrough",
        "ActionFamily": "Training",
        "DeliveryChannel": "Teams",
        "TriggerEvent": "KB adherence fail",
        "AppliesToCriticality": "Business Critical",
        "IshikawaPillar": "Process",
        "OwnerRole": "Supervisor",
        "RequiresSupervisor": True,
        "RequiresQaOwner": False,
        "SlaFeedbackHours": 48,
        "TypicalEffortMinutes": 25,
        "TypicalCostUsd": 35,
        "ExpectedScoreLiftHint": 0.14,
        "BestQmLink": "PHAROS Repeat Fail example: KB adherence",
        "AmazonUseCase": "Agent quoted memory on A-to-z window",
    },
    {
        "CoachingActionID": "ACT-09",
        "ActionName": "Glide-path extension",
        "ActionFamily": "Nesting",
        "DeliveryChannel": "Nest desk",
        "TriggerEvent": "New hire not at proficiency",
        "AppliesToCriticality": "Customer Critical|Business Critical",
        "IshikawaPillar": "People",
        "OwnerRole": "Trainer",
        "RequiresSupervisor": True,
        "RequiresQaOwner": True,
        "SlaFeedbackHours": 0,
        "TypicalEffortMinutes": 0,
        "TypicalCostUsd": 0,
        "ExpectedScoreLiftHint": 0.08,
        "BestQmLink": "New Hire Performance Analysis; extend nesting before floor",
        "AmazonUseCase": "R-squared glide path still below target at day 75",
    },
    {
        "CoachingActionID": "ACT-10",
        "ActionName": "Repeat-fail behavioral deep dive",
        "ActionFamily": "Coaching",
        "DeliveryChannel": "Floor",
        "TriggerEvent": "Same parameter failed 3+ times in 30 days",
        "AppliesToCriticality": "Customer Critical|Business Critical",
        "IshikawaPillar": "People",
        "OwnerRole": "Supervisor",
        "RequiresSupervisor": True,
        "RequiresQaOwner": True,
        "SlaFeedbackHours": 48,
        "TypicalEffortMinutes": 50,
        "TypicalCostUsd": 70,
        "ExpectedScoreLiftHint": 0.16,
        "BestQmLink": "Repeat Fail Analysis; behavioral vs structural split",
        "AmazonUseCase": "Same agent fails QP06 Resolution SOP three weeks running",
    },
    {
        "CoachingActionID": "ACT-11",
        "ActionName": "Escalation-path clinic",
        "ActionFamily": "Training",
        "DeliveryChannel": "Huddle",
        "TriggerEvent": "Escalation accuracy fail",
        "AppliesToCriticality": "Customer Critical",
        "IshikawaPillar": "Process",
        "OwnerRole": "SME",
        "RequiresSupervisor": True,
        "RequiresQaOwner": False,
        "SlaFeedbackHours": 48,
        "TypicalEffortMinutes": 35,
        "TypicalCostUsd": 55,
        "ExpectedScoreLiftHint": 0.13,
        "BestQmLink": "Escalation Accuracy target >90%",
        "AmazonUseCase": "Pharmacy cold-chain sent to general returns",
    },
    {
        "CoachingActionID": "ACT-12",
        "ActionName": "Documentation standards recap",
        "ActionFamily": "Coaching",
        "DeliveryChannel": "Email recap",
        "TriggerEvent": "CRM documentation fail",
        "AppliesToCriticality": "Business Critical",
        "IshikawaPillar": "Process",
        "OwnerRole": "Supervisor",
        "RequiresSupervisor": True,
        "RequiresQaOwner": False,
        "SlaFeedbackHours": 48,
        "TypicalEffortMinutes": 15,
        "TypicalCostUsd": 20,
        "ExpectedScoreLiftHint": 0.09,
        "BestQmLink": "Business Critical example: wrong / missing documentation",
        "AmazonUseCase": "No order ID / no promise time in case",
    },
    {
        "CoachingActionID": "ACT-13",
        "ActionName": "TCD coding calibration",
        "ActionFamily": "Training",
        "DeliveryChannel": "Huddle",
        "TriggerEvent": "Reason-code accuracy fail",
        "AppliesToCriticality": "Business Critical",
        "IshikawaPillar": "Measurement",
        "OwnerRole": "Quality Analyst",
        "RequiresSupervisor": True,
        "RequiresQaOwner": True,
        "SlaFeedbackHours": 48,
        "TypicalEffortMinutes": 20,
        "TypicalCostUsd": 30,
        "ExpectedScoreLiftHint": 0.11,
        "BestQmLink": "Top Contact Driver analysis integrity",
        "AmazonUseCase": "Refund-not-initiated coded as Delivery Delay",
    },
    {
        "CoachingActionID": "ACT-14",
        "ActionName": "Hold and transfer protocol drill",
        "ActionFamily": "Coaching",
        "DeliveryChannel": "Floor",
        "TriggerEvent": "Hold / transfer fail",
        "AppliesToCriticality": "Business Critical",
        "IshikawaPillar": "Process",
        "OwnerRole": "Supervisor",
        "RequiresSupervisor": True,
        "RequiresQaOwner": False,
        "SlaFeedbackHours": 48,
        "TypicalEffortMinutes": 20,
        "TypicalCostUsd": 25,
        "ExpectedScoreLiftHint": 0.08,
        "BestQmLink": "EOF observable behavior; process adherence",
        "AmazonUseCase": "Silent hold >60s or cold transfer to seller",
    },
    {
        "CoachingActionID": "ACT-15",
        "ActionName": "Privacy and authentication checkpoint",
        "ActionFamily": "Compliance",
        "DeliveryChannel": "Teams",
        "TriggerEvent": "QP01 or QP02 fail",
        "AppliesToCriticality": "Compliance Critical",
        "IshikawaPillar": "Compliance",
        "OwnerRole": "Quality Analyst",
        "RequiresSupervisor": True,
        "RequiresQaOwner": True,
        "SlaFeedbackHours": 24,
        "TypicalEffortMinutes": 40,
        "TypicalCostUsd": 150,
        "ExpectedScoreLiftHint": 0.25,
        "BestQmLink": "GDPR / privacy listed as CompC errors; tighter than 48h for fatal",
        "AmazonUseCase": "Full card number or other household address spoken",
    },
    {
        "CoachingActionID": "ACT-16",
        "ActionName": "Golden nugget share-back",
        "ActionFamily": "Coaching",
        "DeliveryChannel": "Huddle",
        "TriggerEvent": "High-score / CSAT save",
        "AppliesToCriticality": "None - positive reinforcement",
        "IshikawaPillar": "People",
        "OwnerRole": "Quality Analyst",
        "RequiresSupervisor": True,
        "RequiresQaOwner": True,
        "SlaFeedbackHours": 0,
        "TypicalEffortMinutes": 15,
        "TypicalCostUsd": 20,
        "ExpectedScoreLiftHint": 0.05,
        "BestQmLink": "Golden Nugget Mining; replicate best practice",
        "AmazonUseCase": "Clean A-to-z save with correct expectation set",
    },
]


def build():
    df = pd.DataFrame(ACTIONS)
    df["IsActive"] = True
    df["Currency"] = "USD"
    df["FeedbackSlaApplies"] = df["SlaFeedbackHours"] > 0
    df["SortOrder"] = range(1, len(df) + 1)
    ordered = [
        "CoachingActionID",
        "ActionName",
        "ActionFamily",
        "DeliveryChannel",
        "TriggerEvent",
        "AppliesToCriticality",
        "IshikawaPillar",
        "OwnerRole",
        "RequiresSupervisor",
        "RequiresQaOwner",
        "SlaFeedbackHours",
        "FeedbackSlaApplies",
        "TypicalEffortMinutes",
        "TypicalCostUsd",
        "Currency",
        "ExpectedScoreLiftHint",
        "BestQmLink",
        "AmazonUseCase",
        "IsActive",
        "SortOrder",
    ]
    return df[ordered]


def main():
    SAVE_FOLDER.mkdir(parents=True, exist_ok=True)
    dim = build()
    if dim["CoachingActionID"].duplicated().any():
        raise ValueError("Duplicate CoachingActionID")
    dim.to_csv(OUTPUT_FILE, index=False)
    print("SUCCESS")
    print("File created:")
    print(OUTPUT_FILE)
    print("Rows:", len(dim))
    print(dim["ActionFamily"].value_counts().to_string())


if __name__ == "__main__":
    main()